import React from 'react'
import BlogCard from '../components/BlogCard'

function BlogPost() {
  return (
    <div className='mx-36 mt-24 text-white'>
        <h1 className='text-6xl text-center mr-20'>Blog Post Title</h1>

        <div className='mx-36 mt-24'>
            <h1 className='font-bold text-4xl'> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Laborum, voluptate!</h1>
            <p className='font-thin tracking-widest mt-6 w-[900px]'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita nihil delectus deleniti mollitia distinctio adipisci. Ullam totam velit nisi qui molestiae eligendi, voluptates ratione fugiat delectus deserunt expedita omnis voluptate porro inventore provident, voluptas vel rem ex. Quae, debitis incidunt. Ipsa aliquam a consectetur, aperiam atque esse nulla mollitia vero eligendi fuga libero quasi optio vel nemo tempore aspernatur! Animi pariatur deleniti, cupiditate nesciunt labore quod facilis nam voluptatem soluta reprehenderit cumque sequi cum reiciendis fugit non voluptatum id beatae exercitationem maxime illum obcaecati voluptates mollitia recusandae nulla. Culpa similique alias non nostrum laudantium veniam totam est iusto voluptatibus esse id enim nulla voluptatem rem, eum dicta. Nobis cupiditate expedita recusandae, hic totam, nulla molestias error omnis saepe quaerat illo fugiat dolore quasi. Dolorum deserunt earum praesentium? <br /><br /> In corrupti odit officia fugit error non dolorem aspernatur! Modi, laborum? Porro dolorem incidunt labore inventore facilis, fugiat nisi hic, unde cupiditate, voluptatum quaerat sint. Nostrum voluptatem enim ab repudiandae neque qui et deleniti dicta, harum eius cum. Obcaecati pariatur, voluptatibus temporibus nam in ipsa esse iure quo consequatur dolores eius illo rem cumque eaque sed fuga perspiciatis ipsam maxime! Eligendi alias cupiditate tenetur at placeat in perspiciatis quaerat deleniti consequatur illo esse, animi aut molestias voluptate dolores exercitationem, atque iusto! Vero, id? Dignissimos beatae voluptatibus ducimus eligendi dolorem sint sapiente veniam odio eos cum aliquam doloremque cumque, ipsa nihil quaerat mollitia accusantium veritatis. Deserunt quas ipsum vel culpa, ducimus dicta est enim inventore incidunt aut unde, dolorum sunt, voluptatum repellat suscipit debitis.</p>
            <h1 className='font-bold text-4xl mt-6'>Lorem ipsum dolor, sit amet consectetur adipisicing.</h1>
            <p className='tracking-widest mt-6 w-[900px]'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt dignissimos laudantium iusto dolores laboriosam tempore praesentium ipsum repellat? Quam rerum laborum illo laboriosam incidunt saepe molestiae voluptas eum iste ullam, amet error modi perspiciatis corrupti officia sunt blanditiis in, impedit exercitationem magni numquam. Iste vitae neque delectus mollitia, est, voluptatum deleniti repellendus totam possimus quaerat reprehenderit, qui assumenda. Itaque consequatur dicta exercitationem voluptatem harum aut, quia optio corrupti odit nisi est rem eius repellat doloribus eveniet in dolor ad excepturi aliquam pariatur voluptate vitae quaerat! Consequuntur, iste! Neque quod commodi sapiente error quaerat quas quo architecto illo, voluptates id aperiam quis natus quibusdam ullam soluta, deleniti illum rem cum! Quo quod quidem, labore maxime eum aspernatur ullam animi ad nisi illo quasi doloremque adipisci officia. Cumque tempore culpa minus ipsum explicabo neque cupiditate iure sequi nostrum autem velit deleniti, tempora laboriosam commodi quos nam placeat quis perspiciatis fuga vitae aliquam.👋👋👋</p>
        </div>
    </div>
  )
}

export default BlogPost